Workaround for "Unsupported class file major version 65" (#15)
The shadowJar task fails with:

    java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)

This is apparently due to the lack of proper support for Java 17+, see:

https://github.com/johnrengelman/shadow/pull/876